package com.slzh.dao.datasource;

import com.slzh.model.datasource.DataItemConfig;
import org.apache.ibatis.annotations.Param;
import org.springframework.security.core.parameters.P;

import java.util.List;
import java.util.Map;

public interface DataItemConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_data_item
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_data_item
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    int insert(DataItemConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_data_item
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    int insertSelective(DataItemConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_data_item
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    DataItemConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_data_item
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    int updateByPrimaryKeySelective(DataItemConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_data_item
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    int updateByPrimaryKey(DataItemConfig record);

    int insertDataItemBybatch(@Param("list") List<DataItemConfig> dataItemConfigList);

    int deleteDataItemConfigBybatch(@Param("ids") List<Long> ids);

    List<DataItemConfig> listDataItemConfig(@Param("params") Map<String,Object> params);


}