package com.slzh.dao.datasource;

import com.slzh.model.datasource.DataItemRelation;
import org.apache.ibatis.annotations.Param;
import org.omg.CORBA.OBJ_ADAPTER;

import java.util.List;
import java.util.Map;

public interface DataItemRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_relation_data_item_set
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_relation_data_item_set
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    int insert(DataItemRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_relation_data_item_set
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    int insertSelective(DataItemRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_relation_data_item_set
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    DataItemRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_relation_data_item_set
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    int updateByPrimaryKeySelective(DataItemRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_relation_data_item_set
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    int updateByPrimaryKey(DataItemRelation record);


    int insertDataItemRelationBybatch(@Param("list") List<DataItemRelation> dataItemRelationList);

    List<Long> deleteDataItemRelationBybatch(@Param("ids") List<Long> ids);

    int updateDataItemRelationBybatch(@Param("list") List<DataItemRelation> dataItemRelationList2);

    List<Map<String,Object>> listDataItemRelation(@Param("params") Map<String, Object> params);
}