package com.slzh.dao.datasource;

import com.slzh.model.datasource.DataSetConfig;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface DataSetConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_data_set
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_data_set
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    int insert(DataSetConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_data_set
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    int insertSelective(DataSetConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_data_set
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    DataSetConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_data_set
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    int updateByPrimaryKeySelective(DataSetConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_data_set
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    int updateByPrimaryKey(DataSetConfig record);


    List<DataSetConfig> listDataSetConfig(@Param("params") Map<String, Object> params);

    int deleteDataSetConfig(@Param("ids") List<Long> dataSetIds);
}