package com.slzh.dao.datasource;

import com.slzh.model.datasource.DataFieldMappingConfig;

public interface DataFieldMappingConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_data_extract_field_mapping
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_data_extract_field_mapping
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    int insert(DataFieldMappingConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_data_extract_field_mapping
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    int insertSelective(DataFieldMappingConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_data_extract_field_mapping
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    DataFieldMappingConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_data_extract_field_mapping
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    int updateByPrimaryKeySelective(DataFieldMappingConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_data_extract_field_mapping
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    int updateByPrimaryKey(DataFieldMappingConfig record);
}