package com.slzh.dao.datasource;

import com.slzh.model.datasource.DataTableMappingConfig;

public interface DataTableMappingConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_data_extract_table_mapping
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_data_extract_table_mapping
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    int insert(DataTableMappingConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_data_extract_table_mapping
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    int insertSelective(DataTableMappingConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_data_extract_table_mapping
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    DataTableMappingConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_data_extract_table_mapping
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    int updateByPrimaryKeySelective(DataTableMappingConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_data_extract_table_mapping
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    int updateByPrimaryKey(DataTableMappingConfig record);
}