package com.slzh.dao;

import ch.qos.logback.core.joran.util.StringToObjectConverter;
import com.slzh.model.desktop.PortalLabel;
import org.apache.ibatis.annotations.Param;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public interface PortalLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_label
     *
     * @mbggenerated Thu Jul 15 11:35:05 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_label
     *
     * @mbggenerated Thu Jul 15 11:35:05 CST 2021
     */
    int insert(PortalLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_label
     *
     * @mbggenerated Thu Jul 15 11:35:05 CST 2021
     */
    int insertSelective(PortalLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_label
     *
     * @mbggenerated Thu Jul 15 11:35:05 CST 2021
     */
    PortalLabel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_label
     *
     * @mbggenerated Thu Jul 15 11:35:05 CST 2021
     */
    int updateByPrimaryKeySelective(PortalLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_label
     *
     * @mbggenerated Thu Jul 15 11:35:05 CST 2021
     */
    int updateByPrimaryKey(PortalLabel record);

    List<PortalLabel> listAllLabels(@Param("params") Map<String, Object> params);

    int deleteLabels(@Param("labelIds") List<Integer> labelIds);

    PortalLabel selectLabelByNameAndType(@Param("labelName")String labelName,@Param("type")Integer type);
}