package com.slzh.dao;


import com.slzh.model.SysMenu;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface SysMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Thu Dec 03 18:48:15 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Thu Dec 03 18:48:15 CST 2020
     */
    int insert(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Thu Dec 03 18:48:15 CST 2020
     */
    int insertSelective(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Thu Dec 03 18:48:15 CST 2020
     */
    SysMenu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Thu Dec 03 18:48:15 CST 2020
     */
    int updateByPrimaryKeySelective(SysMenu record);
    List<Map<String, Object>> listAllFunctionRoleMapping();
    List<Map<String, Object>> listAllMenuInfo();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Thu Dec 03 18:48:15 CST 2020
     */
    int updateByPrimaryKey(SysMenu record);

    List<SysMenu> listMenusByUserId(@Param("userId")Long userId);
    List<SysMenu> listAllMenus();
    List<SysMenu> listAllMenuAuthority();
    List<Map<String, String>> getHaveMenuRoleIds();

    List<Map<String, Object>> getAllApplicationInfo();
}