package com.slzh.model.sso;

import java.util.Date;
import java.util.List;

public class AppCenter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_app_center.register_info_id
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    private Integer labelId;

    public Integer getLabelId() {
        return labelId;
    }

    public void setLabelId(Integer labelId) {
        this.labelId = labelId;
    }

    private String devId;
    private String registerInfoId;
    private String appId;
    // 非数据库字段，在当前收藏夹/桌面是否下载.默认是0
    private int isDownload;

    private List<String> labelIdsStr;

    private List<Integer> labelIds;
    private List<Integer> menuIds;

    public String getDevId() {
        return devId;
    }

    public void setDevId(String devId) {
        this.devId = devId;
    }

    public List<Integer> getLabelIds() {
        return labelIds;
    }

    public void setLabelIds(List<Integer> labelIds) {
        this.labelIds = labelIds;
    }

    public List<String> getLabelIdsStr() {
        return labelIdsStr;
    }

    public AppCenter() {
    }

    public AppCenter(String appId, List<Integer> labelIds) {
        this.appId = appId;
        this.labelIds = labelIds;
    }


    public void setLabelIdsStr(List<String> labelIdsStr) {
        this.labelIdsStr = labelIdsStr;
    }

    public List<Integer> getMenuIds() {
        return menuIds;
    }

    public void setMenuIds(List<Integer> menuIds) {
        this.menuIds = menuIds;
    }

    public String getAppId() {
        return appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    public int getIsDownload() {
        return isDownload;
    }

    public void setIsDownload(int isDownload) {
        this.isDownload = isDownload;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_app_center.developers
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    private String developers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_app_center.application_name
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    private String applicationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_app_center.application_type
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    private Integer applicationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_app_center.ip_address
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    private String ipAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_app_center.mac_address
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    private String macAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_app_center.access_address
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    private String accessAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_app_center.resource_id
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    private Long resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_app_center.resource_desc
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    private String resourceDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_app_center.is_enabled
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    private Integer isEnabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_app_center.license_code
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    private String licenseCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_app_center.inner_license_code
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    private String innerLicenseCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_app_center.remark
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_app_center.is_delete
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_app_center.create_user
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_app_center.create_department
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    private String createDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_app_center.create_server_host
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    private String createServerHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_app_center.create_time
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_app_center.update_user
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_app_center.update_department
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    private String updateDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_app_center.update_server_host
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    private String updateServerHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_app_center.update_time
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_app_center.record_version
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    private Integer recordVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_app_center.download_count
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    private Integer downloadCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_app_center.icon
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    private String icon;

    private String loginLink;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_app_center.register_info_id
     *
     * @return the value of portal_app_center.register_info_id
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public String getRegisterInfoId() {
        return registerInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_app_center.register_info_id
     *
     * @param registerInfoId the value for portal_app_center.register_info_id
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public void setRegisterInfoId(String registerInfoId) {
        this.registerInfoId = registerInfoId == null ? null : registerInfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_app_center.developers
     *
     * @return the value of portal_app_center.developers
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public String getDevelopers() {
        return developers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_app_center.developers
     *
     * @param developers the value for portal_app_center.developers
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public void setDevelopers(String developers) {
        this.developers = developers == null ? null : developers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_app_center.application_name
     *
     * @return the value of portal_app_center.application_name
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public String getApplicationName() {
        return applicationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_app_center.application_name
     *
     * @param applicationName the value for portal_app_center.application_name
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public void setApplicationName(String applicationName) {
        this.applicationName = applicationName == null ? null : applicationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_app_center.application_type
     *
     * @return the value of portal_app_center.application_type
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public Integer getApplicationType() {
        return applicationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_app_center.application_type
     *
     * @param applicationType the value for portal_app_center.application_type
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public void setApplicationType(Integer applicationType) {
        this.applicationType = applicationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_app_center.ip_address
     *
     * @return the value of portal_app_center.ip_address
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_app_center.ip_address
     *
     * @param ipAddress the value for portal_app_center.ip_address
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress == null ? null : ipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_app_center.mac_address
     *
     * @return the value of portal_app_center.mac_address
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public String getMacAddress() {
        return macAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_app_center.mac_address
     *
     * @param macAddress the value for portal_app_center.mac_address
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public void setMacAddress(String macAddress) {
        this.macAddress = macAddress == null ? null : macAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_app_center.access_address
     *
     * @return the value of portal_app_center.access_address
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public String getAccessAddress() {
        return accessAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_app_center.access_address
     *
     * @param accessAddress the value for portal_app_center.access_address
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public void setAccessAddress(String accessAddress) {
        this.accessAddress = accessAddress == null ? null : accessAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_app_center.resource_id
     *
     * @return the value of portal_app_center.resource_id
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public Long getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_app_center.resource_id
     *
     * @param resourceId the value for portal_app_center.resource_id
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public void setResourceId(Long resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_app_center.resource_desc
     *
     * @return the value of portal_app_center.resource_desc
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public String getResourceDesc() {
        return resourceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_app_center.resource_desc
     *
     * @param resourceDesc the value for portal_app_center.resource_desc
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public void setResourceDesc(String resourceDesc) {
        this.resourceDesc = resourceDesc == null ? null : resourceDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_app_center.is_enabled
     *
     * @return the value of portal_app_center.is_enabled
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public Integer getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_app_center.is_enabled
     *
     * @param isEnabled the value for portal_app_center.is_enabled
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public void setIsEnabled(Integer isEnabled) {
        this.isEnabled = isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_app_center.license_code
     *
     * @return the value of portal_app_center.license_code
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public String getLicenseCode() {
        return licenseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_app_center.license_code
     *
     * @param licenseCode the value for portal_app_center.license_code
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public void setLicenseCode(String licenseCode) {
        this.licenseCode = licenseCode == null ? null : licenseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_app_center.inner_license_code
     *
     * @return the value of portal_app_center.inner_license_code
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public String getInnerLicenseCode() {
        return innerLicenseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_app_center.inner_license_code
     *
     * @param innerLicenseCode the value for portal_app_center.inner_license_code
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public void setInnerLicenseCode(String innerLicenseCode) {
        this.innerLicenseCode = innerLicenseCode == null ? null : innerLicenseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_app_center.remark
     *
     * @return the value of portal_app_center.remark
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_app_center.remark
     *
     * @param remark the value for portal_app_center.remark
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_app_center.is_delete
     *
     * @return the value of portal_app_center.is_delete
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_app_center.is_delete
     *
     * @param isDelete the value for portal_app_center.is_delete
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_app_center.create_user
     *
     * @return the value of portal_app_center.create_user
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_app_center.create_user
     *
     * @param createUser the value for portal_app_center.create_user
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_app_center.create_department
     *
     * @return the value of portal_app_center.create_department
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public String getCreateDepartment() {
        return createDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_app_center.create_department
     *
     * @param createDepartment the value for portal_app_center.create_department
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public void setCreateDepartment(String createDepartment) {
        this.createDepartment = createDepartment == null ? null : createDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_app_center.create_server_host
     *
     * @return the value of portal_app_center.create_server_host
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public String getCreateServerHost() {
        return createServerHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_app_center.create_server_host
     *
     * @param createServerHost the value for portal_app_center.create_server_host
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public void setCreateServerHost(String createServerHost) {
        this.createServerHost = createServerHost == null ? null : createServerHost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_app_center.create_time
     *
     * @return the value of portal_app_center.create_time
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_app_center.create_time
     *
     * @param createTime the value for portal_app_center.create_time
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_app_center.update_user
     *
     * @return the value of portal_app_center.update_user
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_app_center.update_user
     *
     * @param updateUser the value for portal_app_center.update_user
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_app_center.update_department
     *
     * @return the value of portal_app_center.update_department
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public String getUpdateDepartment() {
        return updateDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_app_center.update_department
     *
     * @param updateDepartment the value for portal_app_center.update_department
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public void setUpdateDepartment(String updateDepartment) {
        this.updateDepartment = updateDepartment == null ? null : updateDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_app_center.update_server_host
     *
     * @return the value of portal_app_center.update_server_host
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public String getUpdateServerHost() {
        return updateServerHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_app_center.update_server_host
     *
     * @param updateServerHost the value for portal_app_center.update_server_host
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public void setUpdateServerHost(String updateServerHost) {
        this.updateServerHost = updateServerHost == null ? null : updateServerHost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_app_center.update_time
     *
     * @return the value of portal_app_center.update_time
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_app_center.update_time
     *
     * @param updateTime the value for portal_app_center.update_time
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_app_center.record_version
     *
     * @return the value of portal_app_center.record_version
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public Integer getRecordVersion() {
        return recordVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_app_center.record_version
     *
     * @param recordVersion the value for portal_app_center.record_version
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public void setRecordVersion(Integer recordVersion) {
        this.recordVersion = recordVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_app_center.download_count
     *
     * @return the value of portal_app_center.download_count
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public Integer getDownloadCount() {
        return downloadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_app_center.download_count
     *
     * @param downloadCount the value for portal_app_center.download_count
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public void setDownloadCount(Integer downloadCount) {
        this.downloadCount = downloadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_app_center.icon
     *
     * @return the value of portal_app_center.icon
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_app_center.icon
     *
     * @param icon the value for portal_app_center.icon
     *
     * @mbggenerated Mon Apr 19 16:43:20 CST 2021
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }


    public String getLoginLink() {
        return loginLink;
    }

    public void setLoginLink(String loginLink) {
        this.loginLink = loginLink;
    }
}