package com.slzh.model.datasource;

import java.util.Date;

public class DataFieldMappingConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_extract_field_mapping.id
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_extract_field_mapping.taskId
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    private Long taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_extract_field_mapping.sourceTable
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    private String sourceTable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_extract_field_mapping.dataItem
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    private String dataItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_extract_field_mapping.sourceField
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    private Long sourceField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_extract_field_mapping.sourceFieldDescCn
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    private String sourceFieldDescCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_extract_field_mapping.defaultValue
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    private String defaultValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_extract_field_mapping.handlerClass
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    private String handlerClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_extract_field_mapping.paramExpr
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    private String paramExpr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_extract_field_mapping.date2Long
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    private Integer date2Long;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_extract_field_mapping.nullGetFeilds
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    private String nullGetFeilds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_extract_field_mapping.del
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    private Integer del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_extract_field_mapping.end
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    private Integer end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_extract_field_mapping.createTime
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_extract_field_mapping.updateTime
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_extract_field_mapping.id
     *
     * @return the value of t_config_data_extract_field_mapping.id
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_extract_field_mapping.id
     *
     * @param id the value for t_config_data_extract_field_mapping.id
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_extract_field_mapping.taskId
     *
     * @return the value of t_config_data_extract_field_mapping.taskId
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_extract_field_mapping.taskId
     *
     * @param taskId the value for t_config_data_extract_field_mapping.taskId
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_extract_field_mapping.sourceTable
     *
     * @return the value of t_config_data_extract_field_mapping.sourceTable
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public String getSourceTable() {
        return sourceTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_extract_field_mapping.sourceTable
     *
     * @param sourceTable the value for t_config_data_extract_field_mapping.sourceTable
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public void setSourceTable(String sourceTable) {
        this.sourceTable = sourceTable == null ? null : sourceTable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_extract_field_mapping.dataItem
     *
     * @return the value of t_config_data_extract_field_mapping.dataItem
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public String getDataItem() {
        return dataItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_extract_field_mapping.dataItem
     *
     * @param dataItem the value for t_config_data_extract_field_mapping.dataItem
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public void setDataItem(String dataItem) {
        this.dataItem = dataItem == null ? null : dataItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_extract_field_mapping.sourceField
     *
     * @return the value of t_config_data_extract_field_mapping.sourceField
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public Long getSourceField() {
        return sourceField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_extract_field_mapping.sourceField
     *
     * @param sourceField the value for t_config_data_extract_field_mapping.sourceField
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public void setSourceField(Long sourceField) {
        this.sourceField = sourceField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_extract_field_mapping.sourceFieldDescCn
     *
     * @return the value of t_config_data_extract_field_mapping.sourceFieldDescCn
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public String getSourceFieldDescCn() {
        return sourceFieldDescCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_extract_field_mapping.sourceFieldDescCn
     *
     * @param sourceFieldDescCn the value for t_config_data_extract_field_mapping.sourceFieldDescCn
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public void setSourceFieldDescCn(String sourceFieldDescCn) {
        this.sourceFieldDescCn = sourceFieldDescCn == null ? null : sourceFieldDescCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_extract_field_mapping.defaultValue
     *
     * @return the value of t_config_data_extract_field_mapping.defaultValue
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_extract_field_mapping.defaultValue
     *
     * @param defaultValue the value for t_config_data_extract_field_mapping.defaultValue
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue == null ? null : defaultValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_extract_field_mapping.handlerClass
     *
     * @return the value of t_config_data_extract_field_mapping.handlerClass
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public String getHandlerClass() {
        return handlerClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_extract_field_mapping.handlerClass
     *
     * @param handlerClass the value for t_config_data_extract_field_mapping.handlerClass
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public void setHandlerClass(String handlerClass) {
        this.handlerClass = handlerClass == null ? null : handlerClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_extract_field_mapping.paramExpr
     *
     * @return the value of t_config_data_extract_field_mapping.paramExpr
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public String getParamExpr() {
        return paramExpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_extract_field_mapping.paramExpr
     *
     * @param paramExpr the value for t_config_data_extract_field_mapping.paramExpr
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public void setParamExpr(String paramExpr) {
        this.paramExpr = paramExpr == null ? null : paramExpr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_extract_field_mapping.date2Long
     *
     * @return the value of t_config_data_extract_field_mapping.date2Long
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public Integer getDate2Long() {
        return date2Long;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_extract_field_mapping.date2Long
     *
     * @param date2Long the value for t_config_data_extract_field_mapping.date2Long
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public void setDate2Long(Integer date2Long) {
        this.date2Long = date2Long;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_extract_field_mapping.nullGetFeilds
     *
     * @return the value of t_config_data_extract_field_mapping.nullGetFeilds
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public String getNullGetFeilds() {
        return nullGetFeilds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_extract_field_mapping.nullGetFeilds
     *
     * @param nullGetFeilds the value for t_config_data_extract_field_mapping.nullGetFeilds
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public void setNullGetFeilds(String nullGetFeilds) {
        this.nullGetFeilds = nullGetFeilds == null ? null : nullGetFeilds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_extract_field_mapping.del
     *
     * @return the value of t_config_data_extract_field_mapping.del
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_extract_field_mapping.del
     *
     * @param del the value for t_config_data_extract_field_mapping.del
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_extract_field_mapping.end
     *
     * @return the value of t_config_data_extract_field_mapping.end
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public Integer getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_extract_field_mapping.end
     *
     * @param end the value for t_config_data_extract_field_mapping.end
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public void setEnd(Integer end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_extract_field_mapping.createTime
     *
     * @return the value of t_config_data_extract_field_mapping.createTime
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_extract_field_mapping.createTime
     *
     * @param createTime the value for t_config_data_extract_field_mapping.createTime
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_extract_field_mapping.updateTime
     *
     * @return the value of t_config_data_extract_field_mapping.updateTime
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_extract_field_mapping.updateTime
     *
     * @param updateTime the value for t_config_data_extract_field_mapping.updateTime
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}