package com.slzh.model.datasource;

import java.util.Date;

public class DataTableMappingConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_extract_table_mapping.id
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_extract_table_mapping.taskId
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    private Long taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_extract_table_mapping.sourceTable
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    private String sourceTable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_extract_table_mapping.dataSet
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    private String dataSet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_extract_table_mapping.createTime
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_extract_table_mapping.updateTime
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_extract_table_mapping.userId
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_extract_table_mapping.selectParams
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    private String selectParams;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_extract_table_mapping.type
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_extract_table_mapping.del
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    private Integer del;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_extract_table_mapping.id
     *
     * @return the value of t_config_data_extract_table_mapping.id
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_extract_table_mapping.id
     *
     * @param id the value for t_config_data_extract_table_mapping.id
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_extract_table_mapping.taskId
     *
     * @return the value of t_config_data_extract_table_mapping.taskId
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_extract_table_mapping.taskId
     *
     * @param taskId the value for t_config_data_extract_table_mapping.taskId
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_extract_table_mapping.sourceTable
     *
     * @return the value of t_config_data_extract_table_mapping.sourceTable
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public String getSourceTable() {
        return sourceTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_extract_table_mapping.sourceTable
     *
     * @param sourceTable the value for t_config_data_extract_table_mapping.sourceTable
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public void setSourceTable(String sourceTable) {
        this.sourceTable = sourceTable == null ? null : sourceTable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_extract_table_mapping.dataSet
     *
     * @return the value of t_config_data_extract_table_mapping.dataSet
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public String getDataSet() {
        return dataSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_extract_table_mapping.dataSet
     *
     * @param dataSet the value for t_config_data_extract_table_mapping.dataSet
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public void setDataSet(String dataSet) {
        this.dataSet = dataSet == null ? null : dataSet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_extract_table_mapping.createTime
     *
     * @return the value of t_config_data_extract_table_mapping.createTime
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_extract_table_mapping.createTime
     *
     * @param createTime the value for t_config_data_extract_table_mapping.createTime
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_extract_table_mapping.updateTime
     *
     * @return the value of t_config_data_extract_table_mapping.updateTime
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_extract_table_mapping.updateTime
     *
     * @param updateTime the value for t_config_data_extract_table_mapping.updateTime
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_extract_table_mapping.userId
     *
     * @return the value of t_config_data_extract_table_mapping.userId
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_extract_table_mapping.userId
     *
     * @param userId the value for t_config_data_extract_table_mapping.userId
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_extract_table_mapping.selectParams
     *
     * @return the value of t_config_data_extract_table_mapping.selectParams
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public String getSelectParams() {
        return selectParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_extract_table_mapping.selectParams
     *
     * @param selectParams the value for t_config_data_extract_table_mapping.selectParams
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public void setSelectParams(String selectParams) {
        this.selectParams = selectParams == null ? null : selectParams.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_extract_table_mapping.type
     *
     * @return the value of t_config_data_extract_table_mapping.type
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_extract_table_mapping.type
     *
     * @param type the value for t_config_data_extract_table_mapping.type
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_extract_table_mapping.del
     *
     * @return the value of t_config_data_extract_table_mapping.del
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_extract_table_mapping.del
     *
     * @param del the value for t_config_data_extract_table_mapping.del
     *
     * @mbggenerated Wed Jul 28 16:02:39 CST 2021
     */
    public void setDel(Integer del) {
        this.del = del;
    }
}