package com.slzh.model.datasource;

import java.util.Date;
import java.util.List;

public class DataSetConfig {


    List<DataItemRelation> dataItemRelationList;

    public List<DataItemRelation> getDataItemRelationList() {
        return dataItemRelationList;
    }

    public void setDataItemRelationList(List<DataItemRelation> dataItemRelationList) {
        this.dataItemRelationList = dataItemRelationList;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_set.id
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_set.dataSetName
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    private String dataSetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_set.dataSet
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    private String dataSet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_set.dataSetType
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    private Integer dataSetType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_set.description
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_set.status
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_set.sourceDepartment
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    private String sourceDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_set.sourceSystem
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    private String sourceSystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_set.contact
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_set.mobileNum
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    private String mobileNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_set.createTime
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_set.updateTime
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_set.userId
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_set.del
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    private Integer del;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_set.id
     *
     * @return the value of t_config_data_set.id
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_set.id
     *
     * @param id the value for t_config_data_set.id
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_set.dataSetName
     *
     * @return the value of t_config_data_set.dataSetName
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public String getDataSetName() {
        return dataSetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_set.dataSetName
     *
     * @param dataSetName the value for t_config_data_set.dataSetName
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public void setDataSetName(String dataSetName) {
        this.dataSetName = dataSetName == null ? null : dataSetName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_set.dataSet
     *
     * @return the value of t_config_data_set.dataSet
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public String getDataSet() {
        return dataSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_set.dataSet
     *
     * @param dataSet the value for t_config_data_set.dataSet
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public void setDataSet(String dataSet) {
        this.dataSet = dataSet == null ? null : dataSet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_set.dataSetType
     *
     * @return the value of t_config_data_set.dataSetType
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public Integer getDataSetType() {
        return dataSetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_set.dataSetType
     *
     * @param dataSetType the value for t_config_data_set.dataSetType
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public void setDataSetType(Integer dataSetType) {
        this.dataSetType = dataSetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_set.description
     *
     * @return the value of t_config_data_set.description
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_set.description
     *
     * @param description the value for t_config_data_set.description
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_set.status
     *
     * @return the value of t_config_data_set.status
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_set.status
     *
     * @param status the value for t_config_data_set.status
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_set.sourceDepartment
     *
     * @return the value of t_config_data_set.sourceDepartment
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public String getSourceDepartment() {
        return sourceDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_set.sourceDepartment
     *
     * @param sourceDepartment the value for t_config_data_set.sourceDepartment
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public void setSourceDepartment(String sourceDepartment) {
        this.sourceDepartment = sourceDepartment == null ? null : sourceDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_set.sourceSystem
     *
     * @return the value of t_config_data_set.sourceSystem
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public String getSourceSystem() {
        return sourceSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_set.sourceSystem
     *
     * @param sourceSystem the value for t_config_data_set.sourceSystem
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public void setSourceSystem(String sourceSystem) {
        this.sourceSystem = sourceSystem == null ? null : sourceSystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_set.contact
     *
     * @return the value of t_config_data_set.contact
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_set.contact
     *
     * @param contact the value for t_config_data_set.contact
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_set.mobileNum
     *
     * @return the value of t_config_data_set.mobileNum
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public String getMobileNum() {
        return mobileNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_set.mobileNum
     *
     * @param mobileNum the value for t_config_data_set.mobileNum
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public void setMobileNum(String mobileNum) {
        this.mobileNum = mobileNum == null ? null : mobileNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_set.createTime
     *
     * @return the value of t_config_data_set.createTime
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_set.createTime
     *
     * @param createTime the value for t_config_data_set.createTime
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_set.updateTime
     *
     * @return the value of t_config_data_set.updateTime
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_set.updateTime
     *
     * @param updateTime the value for t_config_data_set.updateTime
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_set.userId
     *
     * @return the value of t_config_data_set.userId
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_set.userId
     *
     * @param userId the value for t_config_data_set.userId
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_set.del
     *
     * @return the value of t_config_data_set.del
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_set.del
     *
     * @param del the value for t_config_data_set.del
     *
     * @mbggenerated Wed Jul 28 14:11:01 CST 2021
     */
    public void setDel(Integer del) {
        this.del = del;
    }
}