package com.slzh.model.datasource;

import java.util.Date;

public class DataItemConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_item.id
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_item.dataItemName
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    private String dataItemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_item.alias
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_item.dataItem
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    private String dataItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_item.description
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_item.dataType
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_item.itemLength
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    private String itemLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_item.sourceDepartment
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    private String sourceDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_item.sourceSystem
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    private String sourceSystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_item.contact
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_item.mobileNum
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    private String mobileNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_item.createTime
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_item.updateTime
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_item.userId
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_item.del
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    private Integer del;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_item.id
     *
     * @return the value of t_config_data_item.id
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_item.id
     *
     * @param id the value for t_config_data_item.id
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_item.dataItemName
     *
     * @return the value of t_config_data_item.dataItemName
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public String getDataItemName() {
        return dataItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_item.dataItemName
     *
     * @param dataItemName the value for t_config_data_item.dataItemName
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public void setDataItemName(String dataItemName) {
        this.dataItemName = dataItemName == null ? null : dataItemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_item.alias
     *
     * @return the value of t_config_data_item.alias
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_item.alias
     *
     * @param alias the value for t_config_data_item.alias
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_item.dataItem
     *
     * @return the value of t_config_data_item.dataItem
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public String getDataItem() {
        return dataItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_item.dataItem
     *
     * @param dataItem the value for t_config_data_item.dataItem
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public void setDataItem(String dataItem) {
        this.dataItem = dataItem == null ? null : dataItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_item.description
     *
     * @return the value of t_config_data_item.description
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_item.description
     *
     * @param description the value for t_config_data_item.description
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_item.dataType
     *
     * @return the value of t_config_data_item.dataType
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_item.dataType
     *
     * @param dataType the value for t_config_data_item.dataType
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_item.itemLength
     *
     * @return the value of t_config_data_item.itemLength
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public String getItemLength() {
        return itemLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_item.itemLength
     *
     * @param itemLength the value for t_config_data_item.itemLength
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public void setItemLength(String itemLength) {
        this.itemLength = itemLength == null ? null : itemLength.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_item.sourceDepartment
     *
     * @return the value of t_config_data_item.sourceDepartment
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public String getSourceDepartment() {
        return sourceDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_item.sourceDepartment
     *
     * @param sourceDepartment the value for t_config_data_item.sourceDepartment
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public void setSourceDepartment(String sourceDepartment) {
        this.sourceDepartment = sourceDepartment == null ? null : sourceDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_item.sourceSystem
     *
     * @return the value of t_config_data_item.sourceSystem
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public String getSourceSystem() {
        return sourceSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_item.sourceSystem
     *
     * @param sourceSystem the value for t_config_data_item.sourceSystem
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public void setSourceSystem(String sourceSystem) {
        this.sourceSystem = sourceSystem == null ? null : sourceSystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_item.contact
     *
     * @return the value of t_config_data_item.contact
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_item.contact
     *
     * @param contact the value for t_config_data_item.contact
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_item.mobileNum
     *
     * @return the value of t_config_data_item.mobileNum
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public String getMobileNum() {
        return mobileNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_item.mobileNum
     *
     * @param mobileNum the value for t_config_data_item.mobileNum
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public void setMobileNum(String mobileNum) {
        this.mobileNum = mobileNum == null ? null : mobileNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_item.createTime
     *
     * @return the value of t_config_data_item.createTime
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_item.createTime
     *
     * @param createTime the value for t_config_data_item.createTime
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_item.updateTime
     *
     * @return the value of t_config_data_item.updateTime
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_item.updateTime
     *
     * @param updateTime the value for t_config_data_item.updateTime
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_item.userId
     *
     * @return the value of t_config_data_item.userId
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_item.userId
     *
     * @param userId the value for t_config_data_item.userId
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_item.del
     *
     * @return the value of t_config_data_item.del
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_item.del
     *
     * @param del the value for t_config_data_item.del
     *
     * @mbggenerated Wed Jul 28 11:30:17 CST 2021
     */
    public void setDel(Integer del) {
        this.del = del;
    }
}