package com.slzh.model.datasource;

import java.util.Date;

public class DataTableConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_table.id
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_table.schemeId
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    private Long schemeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_table.dataSourceId
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    private Long dataSourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_table.sourceTableName
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    private String sourceTableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_table.sourceTable
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    private String sourceTable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_table.library
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    private String library;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_table.createTime
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_table.userId
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_table.updateTime
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_data_table.status
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_table.id
     *
     * @return the value of t_config_data_table.id
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_table.id
     *
     * @param id the value for t_config_data_table.id
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_table.schemeId
     *
     * @return the value of t_config_data_table.schemeId
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    public Long getSchemeId() {
        return schemeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_table.schemeId
     *
     * @param schemeId the value for t_config_data_table.schemeId
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    public void setSchemeId(Long schemeId) {
        this.schemeId = schemeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_table.dataSourceId
     *
     * @return the value of t_config_data_table.dataSourceId
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    public Long getDataSourceId() {
        return dataSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_table.dataSourceId
     *
     * @param dataSourceId the value for t_config_data_table.dataSourceId
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    public void setDataSourceId(Long dataSourceId) {
        this.dataSourceId = dataSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_table.sourceTableName
     *
     * @return the value of t_config_data_table.sourceTableName
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    public String getSourceTableName() {
        return sourceTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_table.sourceTableName
     *
     * @param sourceTableName the value for t_config_data_table.sourceTableName
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    public void setSourceTableName(String sourceTableName) {
        this.sourceTableName = sourceTableName == null ? null : sourceTableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_table.sourceTable
     *
     * @return the value of t_config_data_table.sourceTable
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    public String getSourceTable() {
        return sourceTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_table.sourceTable
     *
     * @param sourceTable the value for t_config_data_table.sourceTable
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    public void setSourceTable(String sourceTable) {
        this.sourceTable = sourceTable == null ? null : sourceTable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_table.library
     *
     * @return the value of t_config_data_table.library
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    public String getLibrary() {
        return library;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_table.library
     *
     * @param library the value for t_config_data_table.library
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    public void setLibrary(String library) {
        this.library = library == null ? null : library.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_table.createTime
     *
     * @return the value of t_config_data_table.createTime
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_table.createTime
     *
     * @param createTime the value for t_config_data_table.createTime
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_table.userId
     *
     * @return the value of t_config_data_table.userId
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_table.userId
     *
     * @param userId the value for t_config_data_table.userId
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_table.updateTime
     *
     * @return the value of t_config_data_table.updateTime
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_table.updateTime
     *
     * @param updateTime the value for t_config_data_table.updateTime
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_data_table.status
     *
     * @return the value of t_config_data_table.status
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_data_table.status
     *
     * @param status the value for t_config_data_table.status
     *
     * @mbggenerated Fri Jul 23 15:06:48 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}