package com.slzh.model.datasource;

import java.util.Date;

public class DataItemRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_relation_data_item_set.id
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_relation_data_item_set.dataSet
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    private String dataSet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_relation_data_item_set.dataItem
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    private String dataItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_relation_data_item_set.isNotNull
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    private Integer isNotNull;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_relation_data_item_set.isKey
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    private Integer isKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_relation_data_item_set.isRequired
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    private Integer isRequired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_relation_data_item_set.createTime
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config_relation_data_item_set.updateTime
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_relation_data_item_set.id
     *
     * @return the value of t_config_relation_data_item_set.id
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_relation_data_item_set.id
     *
     * @param id the value for t_config_relation_data_item_set.id
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_relation_data_item_set.dataSet
     *
     * @return the value of t_config_relation_data_item_set.dataSet
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    public String getDataSet() {
        return dataSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_relation_data_item_set.dataSet
     *
     * @param dataSet the value for t_config_relation_data_item_set.dataSet
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    public void setDataSet(String dataSet) {
        this.dataSet = dataSet == null ? null : dataSet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_relation_data_item_set.dataItem
     *
     * @return the value of t_config_relation_data_item_set.dataItem
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    public String getDataItem() {
        return dataItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_relation_data_item_set.dataItem
     *
     * @param dataItem the value for t_config_relation_data_item_set.dataItem
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    public void setDataItem(String dataItem) {
        this.dataItem = dataItem == null ? null : dataItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_relation_data_item_set.isNotNull
     *
     * @return the value of t_config_relation_data_item_set.isNotNull
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    public Integer getIsNotNull() {
        return isNotNull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_relation_data_item_set.isNotNull
     *
     * @param isNotNull the value for t_config_relation_data_item_set.isNotNull
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    public void setIsNotNull(Integer isNotNull) {
        this.isNotNull = isNotNull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_relation_data_item_set.isKey
     *
     * @return the value of t_config_relation_data_item_set.isKey
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    public Integer getIsKey() {
        return isKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_relation_data_item_set.isKey
     *
     * @param isKey the value for t_config_relation_data_item_set.isKey
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    public void setIsKey(Integer isKey) {
        this.isKey = isKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_relation_data_item_set.isRequired
     *
     * @return the value of t_config_relation_data_item_set.isRequired
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    public Integer getIsRequired() {
        return isRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_relation_data_item_set.isRequired
     *
     * @param isRequired the value for t_config_relation_data_item_set.isRequired
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    public void setIsRequired(Integer isRequired) {
        this.isRequired = isRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_relation_data_item_set.createTime
     *
     * @return the value of t_config_relation_data_item_set.createTime
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_relation_data_item_set.createTime
     *
     * @param createTime the value for t_config_relation_data_item_set.createTime
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config_relation_data_item_set.updateTime
     *
     * @return the value of t_config_relation_data_item_set.updateTime
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config_relation_data_item_set.updateTime
     *
     * @param updateTime the value for t_config_relation_data_item_set.updateTime
     *
     * @mbggenerated Wed Jul 28 14:46:19 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}