spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.3.40:3306/data_schedule?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: slzh@mysql2020
#      url: jdbc:mysql://192.168.3.40:3306/multi?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#      username: root
#      password: slzh@mysql2020
      filters: stat,wall,log4j ,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20


pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    com.slzh.dao: DEBUG
    com.slzh: debug


jedis :
  pool :
    host : 320d64d3.nat123.fun
    port : 31596
    password: slzh2020
    config :
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis : 10000

dwLoginUrl: http://localhost:8080/#/login